### ISSUE TITLE
aktueller stand

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/2factor_auth#1]
STATUS: **Technisch Fertig / UI rudimentär**

was geht
- OTP ist getestet mit google authenticator
- barcode kann mittels google authenticator gescanned werden und liefert synchrone OTP werte
- nach login wird OTP abgefragt

mvp todos
- Übersetzungen
- UIs aufhübschen
- User anleiten

nice 2 have
- 2factor auth pro user aktivierbar (im profil) - erfordert https://github.com/redaxo/redaxo/issues/196#issuecomment-451844718
- für admin erzwingen
- für alle user erzwingen
- via console abschaltbar, falls man sich aussperrt

**Comment by staabm** [comment]
der MVP ist fertig. der aktuelle stand sollte funktionieren.

die UI ist noch sehr hässlich und es fehlen übersetzungen, aber getestet werden kann es @skerbis @alexplusde @bloep

**Comment by bloep** [comment]
funktioniert gut 👍 

optional wäre eine Anzeige des SecurityTokens beim Setup neben dem QR-Code gut. Vielleicht könnte man auch ein Anzeigen der Minibar verhindern, solange der Token nicht eingeben wurde.

**Comment by staabm** [comment]
so - paar weitere kleinigkeiten sind implementiert.

es könnte jetzt jemand mit lust und spass an html/css das ganze ein bissl aufhübschen.

**Comment by Hirbod** [comment]
Funktioniert der Ansatz nur mit Google OTP, oder ist das ein offener Standard?
1Password z.B. kann auch als OTP Provider genutzt werden und besitzt die Möglichkeit, QR-Codes von Webseiten einzurichten, um sich als OTP Provider anzubieten.

<img width="597" alt="bildschirmfoto 2019-01-08 um 21 43 04" src="https://user-images.githubusercontent.com/504909/50857669-a1106200-138e-11e9-8567-14c71e2c906c.png">

**Comment by staabm** [comment]
Das addon ist neutral

**Comment by Hirbod** [comment]
1P funzt einwandfrei. Sehr sehr geile Sache!

<img width="364" alt="bildschirmfoto 2019-01-08 um 21 49 47" src="https://user-images.githubusercontent.com/504909/50857959-6529cc80-138f-11e9-8d55-c9ce033df0c6.png">

**Comment by Hirbod** [comment]
Noch meine zwei Cents zu dem Ding:
Die meisten Webseiten, die OTP anbieten, haben noch zusätzlich zum Barcode den "Manualmode", da wird einem ein Code zum abtippen/kopieren angezeigt.

Das ist zum Beispiel super wichtig, wenn man Google OTP auf iOS nutzt, da es keine Backup-Funktion hat und man z.B. beim Verlust eines Smartphones teilweise auf den Support angewiesen und aufgeschmissen ist. Deswegen sollte man diesen "Backup" mit anzeigen, das man sich dem z.B ausdruckt oder irgendwo auf nen USB Stick packt, um im Zweifel den OTP wiederherzustellen.

**Comment by staabm** [comment]
Ok danke, habs mal als separates issue angelegt

**Comment by alexplusde** [comment]
> 2factor auth pro user aktivierbar (im profil) - erfordert redaxo/redaxo#196 (comment)

Ohne es im Profil unterzubringen geht es ja jetzt schon via Menü, wenn ich das richtig sehe. Wäre es alternativ möglich, das Profil mit Tabs zu unterteilen, wie es an anderen Addons möglich ist, und 2-factor-auth somit als Unterseite zu nutzen?

**Comment by staabm** [comment]
> Ohne es im Profil unterzubringen geht es ja jetzt schon via Menü, wenn ich das richtig sehe. Wäre es alternativ möglich, das Profil mit Tabs zu unterteilen, wie es an anderen Addons möglich ist, und 2-factor-auth somit als Unterseite zu nutzen?

das müsste man mal schauen. vermutlich geht das. bitte separates issue.
