### ISSUE TITLE
recovery code / manual mode

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/2factor_auth#13]
> Noch meine zwei Cents zu dem Ding:
Die meisten Webseiten, die OTP anbieten, haben noch zusätzlich zum Barcode den "Manualmode", da wird einem ein Code zum abtippen/kopieren angezeigt.
>
> Das ist zum Beispiel super wichtig, wenn man Google OTP auf iOS nutzt, da es keine Backup-Funktion hat und man z.B. beim Verlust eines Smartphones teilweise auf den Support angewiesen und aufgeschmissen ist. Deswegen sollte man diesen "Backup" mit anzeigen, das man sich den Secret z.B ausdruckt oder irgendwo auf nen USB Stick packt, um im Zweifel den OTP wiederherzustellen.
>
>Die Daten dazu scheinen auch anscheinend bereits im Input-Feld vorhanden. Sollte man noch gesondert anzeigen.

_Originally posted by @Hirbod in 

https://github.com/FriendsOfREDAXO/2factor_auth/issues/1#issuecomment-452447227

**Comment by alexplusde** [comment]
Achso...

**Comment by staabm** [comment]
> Ne.. Es geht um die Ausgabe des Inhaltes des QR-Codes.

der inhalt des qr codes wird bereits in einem textfeld am qr code (dort ist auch ein copy/paste) knopf

https://github.com/FriendsOfREDAXO/2factor_auth/blob/087fedc6126dd6ebfdb93348a36a06345f10114c/pages/setup.php#L34

**Comment by Hirbod** [comment]
Das ist richtig, man benötigt aber nicht den kompletten Inhalt, sondern nur einen Teil davon, damit man z.B. in der Google Auth App den OTP manuell hinzufügen kann. 

![img_3440](https://user-images.githubusercontent.com/504909/51175151-c5ea6500-18b9-11e9-91ff-16e76d67c360.PNG)

**Comment by alxndr-w** [comment]
Nachdem meine Beiträge Mitte des Jahres weder in den Relase Notes, noch in der README gewürdigt wurden, kann das ruhig jemand anderes machen.
