### ISSUE TITLE
Wooops nach dem Login (Kollision mit der minibar?)

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/2factor_auth#15]
Update von REDAXO und allen Addons gemacht.
Danach 2factor_auth installiert, eingerichtet und ausprobiert.

Nach dem Login kommt der (das?) Wooops

![image](https://user-images.githubusercontent.com/330516/50883155-88806600-13e7-11e9-9b6e-260614c3a917.png)

<details>
<summary>System report (REDAXO 5.7.0-beta1, PHP 7.2.7)</summary>

| REDAXO        |             |
| ------------: | :---------- |
|       Version | 5.7.0-beta1 |

| PHP           |            |
| ------------: | :--------- |
|       Version | 7.2.7      |
|       OPcache | no         |
|        Xdebug | yes        |

| Database      |                        |
| ------------: | :--------------------- |
|       Version | 5.7.21                 |
| Character set | utf8 (utf8_general_ci) |

| Server        |            |
| ------------: | :--------- |
|            OS | Darwin     |
|          SAPI | cgi-fcgi   |
|     Webserver | Apache     |

| Request       |                     |
| ------------: | :------------------ |
|       Browser | Chrome/71.0.3578.98 |
|      Protocol | HTTP/1.1            |
|         HTTPS | yes                 |

| Packages                    |             |
| --------------------------: | :---------- |
|                2factor_auth | 1.0.0-beta1 |
|                     adminer | 1.5.0       |
|                      backup | 2.3.0-beta1 |
|                    be_style | 2.7.0-beta1 |
|         be_style/customizer | 2.7.0-beta1 |
|             be_style/redaxo | 2.7.0-beta1 |
|                     cronjob | 2.4.0-beta1 |
|                   developer | 3.8.0       |
|                     install | 2.4.1-beta1 |
|                    markitup | 3.2.0       |
|               media_manager | 2.6.0-beta1 |
|                   mediapool | 2.5.0-beta1 |
|                    metainfo | 2.3.2-beta1 |
|                       mform | 5.2.4       |
|               modulsammlung | 4.13.1      |
| modulsammlung/documentation | 1.0         |
|                        out5 | 1.0         |
|                 out5/border | 0.1         |
|              out5/email_url | 0.1         |
|            out5/login_image | 0.1         |
|                    out5/min | 0.1         |
|                   phpmailer | 2.5.0-beta1 |
|            quick_navigation | 3.5.4       |
|            rex5_multiupload | 1.0.2       |
|                rex_redactor | 1.6.5       |
|                   search_it | 6.6.3       |
|     search_it/documentation | 6.6.3       |
|         search_it/plaintext | 6.6.3       |
|             search_it/stats | 6.6.3       |
|                       sprog | 1.1.0       |
|                   structure | 2.7.0-beta1 |
|           structure/content | 2.7.0-beta1 |
|                       theme | 1.1.1       |
|                         url | 1.0.1       |
|                       users | 2.5.2-beta1 |
|                       yform | 3.0-beta7   |
|                  yform/docs | 3.0-beta7   |
|                 yform/email | 3.0-beta7   |
|                   yform/geo | 2.3-b5      |
|               yform/manager | 3.0-beta7   |
|                 yform/tools | 3.0-beta7   |
|                    yrewrite | 2.4         |

</details>

**Comment by staabm** [comment]
Dazu brauchst du eine aktuellere redaxo 5.7 als beta1

**Comment by olien** [comment]
ok. danke
