### ISSUE TITLE
Nach dem Aktivieren von 2factor-auth ohne 2factor-auth eingeloggt

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/2factor_auth#16]
Ich habe 2factor-auth aktiviert, eingerichtet, abgemeldet und dann direkt wieder angemeldet - und war direkt eingeloggt.

Im Inkognito-Modus hingegen wurde ich dann nach dem Code gefragt.

**Comment by staabm** [comment]
ich hatte das problems so bisher nicht. vllt kannst du ein kleines video oder noch genauer die step-to-reproduce mit paar screenshots machen

**Comment by bloep** [comment]
ich das Verhalten im Safari reproduzieren.

**Comment by bloep** [comment]
das Problem ist, dass der Core beim Logout `Clear-Site-Data`-Header verwendet um die Cookies (inkl. Session Cookie) zu entfernen. Der Safari unterstützt diesen Header nicht, sodass die PHP-Session weiterhin aktiv bleibt.
Dadurch bleibt dann auch die Session-Var auf `true`
https://github.com/FriendsOfREDAXO/2factor_auth/blob/9af726fcda744406ee9f13dcf782a6baef1162bc/lib/one_time_password.php#L36-L39

**Comment by staabm** [comment]
und in anderen browsern nicht? kannst du die fragen aus dem kommentar darüber beantworten?

**Comment by bloep** [comment]
sehe ich auch so. Bitte Issue aufmachen.

**Comment by alexplusde** [comment]
Wurde scheinbar gefixt. Wenn das Problem wieder besteht, erneut aufmachen...
