### ISSUE TITLE
Beschriftung innerhalb FreeOTP

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/2factor_auth#17]
Die Lösung ist ja kompatibel zu Apps wie FreeOTP, damit teste ich das Addon gerade.

Hier wäre es sinnvoll, als Benutzer den Loginnamen zu zeigen (roter Kasten) sowie oberhalb davon nicht `die E-Mail-Adresse + den Titel der Website`, sondern vlt. `REDAXO CMS domain.de` oder `REDAXO CMS Websitetitel`

![image](https://user-images.githubusercontent.com/3855487/51172905-94bb6600-18b4-11e9-9842-8aaf93e1d0fc.png)

**Comment by staabm** [comment]
als in meinem google authenticator sehe ich ein label mit genau diesen daten.

ggf. muss man für freeotp noch was gesondert tun.

PR welcome.

**Comment by staabm** [comment]
> ich mach mich mal schlau. Das Favicon der Website bspw. auch darzustellen fände ich sinnvoll - oder ein Icon im Backend auswählen zu können.

gerne als separates issue
