### ISSUE TITLE
Design der Code-Eingabe-Seite während Login

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/2factor_auth#18]
Ich stelle mir vor, dass das ziemlich analog zur Login-Seite aussieht, wenn man den Code eingibt:

![image](https://user-images.githubusercontent.com/3855487/51173138-11e6db00-18b5-11e9-9c3e-3ba33a1617dc.png)

**Comment by staabm** [comment]
ich habe bisher nur das wirklich technische minimum umgesetzt. bin hier definitiv für besserungen im workflow und design offen

**Comment by alexplusde** [comment]
@staabm das verstehe ich. Ich werde meinen Teil dazu leisten und hoffe, es wird ein richtiges FOR-Addon, bei dem wir gemeinsam was daran entwickeln.

**Comment by Hirbod** [comment]
Ich würde mir wünschen, dass das AddOn später aber Core-Bestandteil wird (sobald es wirklich ausgearbeitet und rund ist). Sicherheit sollte man nicht als AddOn zuschalten müssen. 

Super Arbeit bisher von euch!

**Comment by staabm** [comment]
> Ich würde mir wünschen, dass das AddOn später aber Core-Bestandteil wird (sobald es wirklich ausgearbeitet und rund ist). Sicherheit sollte man nicht als AddOn zuschalten müssen.

das ist das ziel. aber zunächst müssen wir es erstmal rund machen.

**Comment by eaCe** [comment]
Da man zu dem Zeitpunkt schon angemeldet ist sieht man halt die REDAXO-Navigation.
Wenn man es einfach so dem Stil anpasst könnte es so aussehen...:

![Bildschirmfoto am 2022-05-26 um 17 55 56](https://user-images.githubusercontent.com/2708231/170526221-11fb3b09-9c99-42c4-beff-0d5deeaf0ad2.png)

![Bildschirmfoto am 2022-05-26 um 17 55 48](https://user-images.githubusercontent.com/2708231/170526227-1d36e55f-5928-4c5a-a199-5d0d7d848412.png)

**Comment by alxndr-w** [comment]
Siehe #33 - es wäre vielleicht klüger, andere Addons und das Menü von der Ausgabe abzuhalten und sich eher an dem zu orientieren, was be_password macht und einen in der Optik in der Login-Seite zu halten. Die Login-Seiten sind ja auch inzwischen Fragmente und könnten daher vlt. gut übernommen werden?

**Comment by eaCe** [comment]
Alles klar, ich schau es mir an.

**Comment by eaCe** [comment]
So vielleicht
![Bildschirmfoto am 2022-05-26 um 19 23 00](https://user-images.githubusercontent.com/2708231/170541775-92c4fb44-1ff5-4bdc-9d98-f5c9d242aa36.png)
