### ISSUE TITLE
wie soll der login prozess aussehen/von statten gehen

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/2factor_auth#2]
design vorschläge?
prozess?

**Comment by staabm** [comment]
@alexplusde ideen dazu?

**Comment by staabm** [comment]
@alexplusde ideen dazu?

**Comment by alexplusde** [comment]
Ist untergegangen, ich denke, da sollte man noch was machen...

**Comment by staabm** [comment]
Wenn du möchtest gerne. Da die grundlegenden dinge da sind hatte ich mal zu gemacht. 

Ideen sind willkommen

**Comment by staabm** [comment]
Ich mach ich hier mal zu... wenn jemand konkrete vorschläge oder ideen hat, gerne neues issue aufmachen
