### ISSUE TITLE
YCom 2-Faktor-Authentifizierung ermöglichen

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/2factor_auth#20]
Gibt es out of the box eine Möglichkeit, ein YCom-Value für den Login zur Verfügung zu stellen?

**Comment by dergel** [comment]
Ich sage mal, nein, nicht out of the box. Habe es aber bei ycom als Issue eingetragen. Ich hatte bisher keinen Bedarf, aber wenn es genug Leute gibt, kann man das ja dort nachziehen.

https://github.com/yakamara/redaxo_ycom/issues/413
