### ISSUE TITLE
Favicon als Icon in der Auth-App nutzen

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/2factor_auth#21]
bspw. bei FreeOTP, aber sicherlich auch anderen Apps vorhanden. Alternativ ein Logo, das man gezielt aus dem Medienpool wählen kann. Was wäre hier gewünscht?

**Comment by staabm** [comment]
sollte ggf. nur das favicon der website verwendet werden?

wir brauchen kein separates favicon nur für 2fa

**Comment by alexplusde** [comment]
Vom Prinzip her bin ich derselben Meinung, dann müsste allerdings sichergestellt sein, dass auch das richtige verwendet wird. Es gibt ja einige Standards, die sich jetzt etabliert haben, bspw. der Pfad zu einem hochauflösenden Apple-iOS-Icon.

Können wir ja definieren.
