### ISSUE TITLE
„Diesen Computer merken“

### ISSUE THREAD

**Issue by hirbod** [FriendsOfREDAXO/2factor_auth#24]
Einige Tools (wie z.b mein Ticketing System Zammad) haben eine Open Source lib im Einsatz, die merkt, wenn man von einem neuen Rechner oder anderem Ort eingeloggt wird. Dann wird eine Warnmeldungen per Mail verschickt und 2FA aktiviert. Die genutzte lib kann ich in Erfahrung bringen, wollte nur fragen ob es Sinn macht, erkannte Computer vom 2FA für z.B 14 Tage oder n-Tagen (oder Stunden) auszuschließen?

Oder soll knallhart jeder Login gesichert sein?

**Comment by staabm** [comment]
ich bin von meiner seite her offen - wenn sowas gewünscht ist von den verwendern des addons kann man sowas bauen.

wenn es eine option ist, die von keinem genutzt wird - eher nicht ;-)

**Comment by eaCe** [comment]
Ich kenne mich damit nicht gut genug aus, wäre es etwas in dieser Richtung? 
https://github.com/gbirke/rememberme

**Comment by alexwenz** [comment]
+1

(da gerade von einem Kunden gefragt, ob es nicht die Option gäbe, den aktuellen Browser für eine bestimmte Zeit zu merken)

**Comment by dergel** [comment]
ich schließe das hier mal. Die OTP Verifizierung wird in der Session gespeichert. Man kann in in REDAXO die Session so definieren wie man sie gerne hätte, Browser schließen, Dauer etc. Deswegen würde ich sagen, dass es damit passen sollte - wenn es auch nicht exakt der Wunsch ist.
