### ISSUE TITLE
Parameter für manuellen Modus im Backend neben QR-Code anzeigen

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/2factor_auth#25]
![bildschirmfoto 2019-02-01 um 09 37 55](https://user-images.githubusercontent.com/791247/52111931-66a08a80-2605-11e9-9ffc-9138469613b2.png)

**Comment by staabm** [comment]
ich habe das tool nicht genutzt, ggf. kann @alexplusde was dazu sagen.

Meine Vermutung:
das ist der manuelle modus, d.h. dort gibts du manuell deinen redaxo username und das secret ein (das du im 2auth setup im redaxo siehst).
Issuer ist ein beliebiger String der dir hilft dich daran zu erinnern wofür der login ist.

Ich habe das ganze mit Google Authenticator getestet. Dort kann man in der App direkt die Kamera starten, den Barcode scannen und muss nichts mehr tun sonst.

**Comment by alexplusde** [comment]
Ich nutze FreeOTP und 1Password als Generator - @skerbis was ist das für ein Tool?

Hast du die Readme schon durch?

**Comment by skerbis** [comment]
habe es aus dem Appstore. Ist ein lokales OTP aufm Mac

In order to add an Account to the OTP Manager, you need the pre-generated secret from the site or application you wish to add the account for. The OTP Manager does not enable Two Factor Authentication, this must be enabled with the Issuer.

To add an account to the manager, do any of the following:

⌘ + N
The Main Menu > File > New Account
Press the + button
It will open a dialogue prompting for 3 inputs:

Issuer - The site or app you are creating the OTP Token for
Username - The username for your account with the Issuer
OTP Secret - The base63 secret generated within the Issuers application

**Comment by skerbis** [comment]
Alles klar, es hat funktionier wie Markus sagt. 

Issuer: Domain der Website
Username: REDAXO user
Secret: aus der URL kopiert. 

Könnt ihr das Secret bitte direkt zeigen, ohne dass es aus dem Link kopiert werden muss?

**Comment by alexplusde** [comment]
Sorry, ist ja noch was offen heir.

**Comment by staabm** [comment]
> Könnt ihr das Secret bitte direkt zeigen, ohne dass es aus dem Link kopiert werden muss?

hmm das "secret" sollte per copy/paste button direkt über dem qrcode bereits einfach greifbar sein, oder?

**Comment by skerbis** [comment]
Nein, da kommt eine vollständige url. Man braucht aber in diesem Fall das was hinter secret= steht
