### ISSUE TITLE
Class 'rex_minibar' not found in Redaxo 5.7.0

### ISSUE THREAD

**Issue by danspringer** [FriendsOfREDAXO/2factor_auth#26]
Nach Update auf Redaxo 5.7.0.
Das sagt das Log:

> redaxo/src/addons/2factor_auth/boot.php - Zeile 9

**Comment by staabm** [comment]
Danke, behoben. Ist das addon im installer - ich weiß es gar nicht mehr :)

**Comment by danspringer** [comment]
Yes, ist im Installer und hat auch gut funktioniert :-)
