### ISSUE TITLE
Release in den installer laden

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/2factor_auth#28]
Kann jemand die aktuelle version in den installer laden?

@alexplusde @skerbis  vllt?

**Comment by schuer** [comment]
Und danach das 🐣 Küken wegmachen bitte :)

**Comment by skerbis** [comment]
Da das release schon fertig war, habe ich das Küken nachträglich vor dem Upload entfernt. Also Release im Installer unterscheidet sich durch ein Zeichen von dem in GitHub.

**Comment by staabm** [comment]
@skerbis danke
