### ISSUE TITLE
Webauthn als Alternative Authentifizierungsmethode validieren

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/2factor_auth#29]
https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API
https://webauthn.guide/
https://w3c.github.io/webauthn/

Damit sollte toucheid/faceid etc funktionieren

**Comment by staabm** [comment]
github nutzt es jetzt auch: https://github.blog/2019-08-21-github-supports-webauthn-for-security-keys/

**Comment by staabm** [comment]
php library dazu: https://github.com/lbuchs/WebAuthn

**Comment by gharlan** [comment]
WebAuthn ist ja inzwischen im Core, daher kann hier vermutlich geschlossen werden. Es wäre höchstens die Frage, ob das 2F-Addon auf die Passkeys im Core reagieren sollte/müsste. Also ob bei Nutzung der Passkeys überhaupt die 2F-Auth noch nötig ist.
Mein Eindruck ist, dass die meisten Seiten auf 2F verzichten, wenn man sich per Passkey (WebAuthn) einloggt, weil bei Passkeys schon eine Art zweiter Faktor enthalten ist.
