### ISSUE TITLE
Quick Navigation wird im Login angezeigt

### ISSUE THREAD

**Issue by Geri2017** [FriendsOfREDAXO/2factor_auth#33]
Obwohl noch nicht eingeloggt, wird die Quick Navigation schon angezeigt…
Bug? Oder Quick Navigation Bug?

![Bildschirmfoto 2019-08-21 um 16 49 34](https://user-images.githubusercontent.com/45007596/63502838-a8741e00-c4ce-11e9-9fb2-3228f0446355.png)

**Comment by staabm** [comment]
gute frage. @skerbis kannst du das auf quick navi seite einfach beheben?

**Comment by skerbis** [comment]
Ist mir nicht klar wie? Ich prüfe ja schon hier: https://github.com/FriendsOfREDAXO/quick_navigation/blob/ec9c5668bab11431c5699a8d9cd7943e25e5ba47/boot.php#L13

**Comment by skerbis** [comment]
Bitte Github Version von Quicknavi testen. Ich close das hier mal

**Comment by staabm** [comment]
https://github.com/FriendsOfREDAXO/quick_navigation/issues/111#issuecomment-524181268

**Comment by skerbis** [comment]
@staabm Ich vermute ob man es evtl. nicht sogar core-seitig lösen müsste. Es ist ja durchaus möglich dass auch andere AddOns einen ½ Logged-In-status brauchen.

**Comment by staabm** [comment]
> Für mich scheint es, dass der User hier ja doch irgendwie eingeloggt ist aber nur gehindert wird weiterzukommen.

so ist es.. ich müsste vom addon her unterbinden dass EPs aufgerufen werden

ich denke dass für den testbaloon hier das ganz so ausreicht. wenn man 2factor im core dann später etablieren will kann man dann "genauer" hinsehen

**Comment by Geri2017** [comment]
Danke! Alles prima!

**Comment by staabm** [comment]
Ich schau auch nochmal, da vermutlich ähnliches Problem mit anderen addons

**Comment by alxndr-w** [comment]
Idee: Hier könnte man vermutlich den vormals generierten Output komplett leeren und die Login-Seite ausgeben und mit exit alles weitere beenden.
