### ISSUE TITLE
2factor lässt sich umgehen, insbesondere bei Admin-Accounts

### ISSUE THREAD

**Issue by gharlan** [FriendsOfREDAXO/2factor_auth#38]
Aktuell kann man den 2-Faktor-Schutz noch umgehen, über den Safemode.

Bei Redakteuren kann man dann "nur" das Profil ändern, also zum Beispiel das Passwort.
Bei Admin-Accounts kann man sich hingegen aber ein Backup ziehen, etwas importieren, und Addons verwalten. Also zum Beispiel 2factor_auth deinstallieren, und dann den Safemode verlassen.

Verhindern ließe sich das wahrscheinlich, wenn sich 2factor_auth selbst in die config.yml bei den `setup_addons` eintragen würde (im Safemode werden die setup_addons geladen). Ggf. muss dann noch in der boot.php ein `if (!rex::isSetup) ...` ergänzt werden.

**Comment by alxndr-w** [comment]
Als Admin könnte man generell auch manipulieren, wie man möchte, das sehe ich nicht als zusätzliche Gefahr.

Das mit den Redakteuren ließe sich über die config.yml regeln.

**Comment by gharlan** [comment]
> Als Admin könnte man generell auch manipulieren, wie man möchte, das sehe ich nicht als zusätzliche Gefahr.

Bin mir nicht sicher, ob wir uns missverstehen. Es geht doch darum, die Accounts zusätzlich zu schützen durch die 2-Factor-Authentication. Und dieser zusätzliche Schutz besteht nicht wirklich, da er umgangen werden kann.
Wer also Admin-Benutzername und Kennwort kennt/rät, kommt ins System, genauso, wie wenn die 2-Factor-Authentication gar nicht aktiv wäre. Man muss aber halt von dem Trick wissen.

**Comment by alxndr-w** [comment]
Jetzt habe ich den Angriffsvektor verstanden.
