### ISSUE TITLE
Label must not contain a colon

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/2factor_auth#5]
![screenshot 2019-01-06 at 23 16 05](https://user-images.githubusercontent.com/1297466/50742270-12bea380-1209-11e9-8895-6c9ff7f4e28f.png)

**Assert\InvalidArgumentException:** Label must not contain a colon.
**File:** redaxo/src/addons/2factor_auth/vendor/beberlei/assert/lib/Assert/Assertion.php
**Line:** 2550

<details>
<summary>Stacktrace</summary>

| Function                                 | File                                                                           | Line     |
| ---------------------------------------- | ------------------------------------------------------------------------------ | -------- |
| Assert\Assertion::createException        | redaxo/src/addons/2factor_auth/vendor/beberlei/assert/lib/Assert/Assertion.php | 1658     |
| Assert\Assertion::false                  | redaxo/src/addons/2factor_auth/vendor/spomky-labs/otphp/src/ParameterTrait.php | 202      |
| OTPHP\OTP->OTPHP\{closure}               | redaxo/src/addons/2factor_auth/vendor/spomky-labs/otphp/src/ParameterTrait.php | 185      |
| OTPHP\OTP->setParameter                  | redaxo/src/addons/2factor_auth/vendor/spomky-labs/otphp/src/ParameterTrait.php | 84       |
| OTPHP\OTP->setLabel                      | redaxo/src/addons/2factor_auth/lib/one_time_password_config.php                | 50       |
| rex_one_time_password_config->init       | redaxo/src/addons/2factor_auth/lib/one_time_password_config.php                | 25       |
| rex_one_time_password_config::loadFromDb | redaxo/src/addons/2factor_auth/pages/setup.php                                 | 25       |
| include                                  | redaxo/src/core/lib/packages/package.php                                       | 228      |
| rex_package->includeFile                 | redaxo/src/core/lib/be/controller.php                                          | 471      |
| rex_be_controller::includePath           | redaxo/src/core/lib/be/controller.php                                          | 413      |
| rex_be_controller::includeCurrentPage    | redaxo/src/core/backend.php                                                    | 196      |
| require                                  | redaxo/src/core/boot.php                                                       | 152      |
| require                                  | redaxo/index.php                                                               | 9        |

</details>
<details>
<summary>System report (REDAXO 5.7.0-beta1, PHP 7.3.0)</summary>

| REDAXO        |             |
| ------------: | :---------- |
|       Version | 5.7.0-beta1 |

| PHP           |            |
| ------------: | :--------- |
|       Version | 7.3.0      |
|       OPcache | no         |
|        Xdebug | no         |

| Database      |                                |
| ------------: | :----------------------------- |
|       Version | 5.5.5-10.4.1-MariaDB-1:10.4.1+maria~bionic |
| Character set | latin1 (latin1_swedish_ci)     |

| Server        |                |
| ------------: | :------------- |
|            OS | Linux          |
|          SAPI | apache2handler |
|     Webserver | Apache/2.4.25  |

| Request       |                     |
| ------------: | :------------------ |
|       Browser | Chrome/71.0.3578.98 |
|      Protocol | HTTP/1.1            |
|         HTTPS | no                  |

| Packages          |             |
| ----------------: | :---------- |
|      2factor_auth | 1.0.0-beta1 |
|            backup | 2.3.0-beta1 |
|          be_style | 2.7.0-beta1 |
|   be_style/redaxo | 2.7.0-beta1 |
|      cache_warmup | 3.5.0       |
|         demo_base | 2.6.4       |
|         developer | 3.8.0       |
|           install | 2.4.1-beta1 |
|          markitup | 3.2.0       |
|     media_manager | 2.6.0-beta1 |
|         mediapool | 2.5.0-beta1 |
|          metainfo | 2.3.2-beta1 |
|         phpmailer | 2.5.0-beta1 |
|           project | dev         |
|         redactor2 | 3.5.0       |
|             sprog | 1.1.0       |
|         structure | 2.7.0-beta1 |
| structure/content | 2.7.0-beta1 |
|             users | 2.5.2-beta1 |
|             yform | 3.0-beta6   |
|        yform/docs | 3.0-beta6   |
|       yform/email | 3.0-beta6   |
|     yform/manager | 3.0-beta6   |

</details>

**Comment by staabm** [comment]
Danke. Vermutlich enthält dein rex-servername oder der http-host einen port. 

Muss ich rausfilter ln

**Comment by schuer** [comment]
Ja genau, 20080.
