### ISSUE TITLE
Erzwinge Nutzung, Einstellungsmöglichkeit dazu

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/2factor_auth#58]
Übertragen aus #1 

Optional
- für admin erzwingen
- für alle user erzwingen

Dazu muss bei abgeschaltetem OTP nach dem Login die Einrichtungs-Seite aufgerufen werden.

**Comment by staabm** [comment]
via system setting jetzt für alle user erzwingbar: https://github.com/FriendsOfREDAXO/2factor_auth/commit/fee2d9be4334ab1371292ca4724c9236d2b145d6
