### ISSUE TITLE
Period bei E-Mail ist eine Minute - das ist zu knapp

### ISSUE THREAD

**Issue by dergel** [FriendsOfREDAXO/2factor_auth#69]
wenn eine E-Mail mal durch Filtersysteme etc erst durchmuss, kann es schon mal ein paar Minuten dauern. Ich würde 5 Minuten als Ok empfinden. (Oder konfigurierbar)

**Comment by dergel** [comment]
klappt leider doch nicht nicht.. ist noch offen https://github.com/FriendsOfREDAXO/2factor_auth/pull/71

**Comment by eaCe** [comment]
@dergel bei mir funktioniert es soweit.
Eventuell hilft das hier? https://github.com/Spomky-Labs/otphp/blob/v11.0/doc/Window.md#window-and-totp
Z.B. `return Factory::loadFromProvisioningUri($provisioningUrl)->verify($otp, null, 30);`

**Comment by dergel** [comment]
Nach meinen Tests klappt es nun. Hatte bei anderen auch nachgefragt und auch dort sind keine entsprechenden Fehler mehr aufgetaucht. ich schließe
