### ISSUE TITLE
otphp library updaten

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/2factor_auth#80]
von der verwendeten https://github.com/Spomky-Labs/otphp bibliothek gibt es 2 neuere major versionen.

wir sollten updates in auge fassen.

evtl muss man auch wg. der mindest php version aufpassen.
aber da es bei 2 factor auth um sicherheit geht, sollte man vermutlich nicht zu konservativ mit der php version umgehen, um die sicherheit derjenigen die aktuelle php versionen verwenden nicht zu gefährden

**Comment by dergel** [comment]
ist aktualisiert
