### ISSUE TITLE
Aktuelle Version fehlt im Installer - Release nötig

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/2factor_auth#83]
**Description / Beschreibung**
Es sind noch Fehler in der Oberfläche wie dieser hier:

![image](https://user-images.githubusercontent.com/3855487/229089948-a16fcf32-e086-4716-9ac1-46b4aac57280.png)

**Comment by eaCe** [comment]
Ping @staabm  :)
