### ISSUE TITLE
2 Wege Authentifikation für einen User deaktivieren - ansonsten "Erzwungen für alle REDAXO-CMS Benutzer"

### ISSUE THREAD

**Issue by steri-rex** [FriendsOfREDAXO/2factor_auth#88]
Ich nutze das Addon 2factor_auth und es sollen alle Redaxo-User zwingend die 2 Wege Authentifikation nutzen bis auf einen User. Dieser User hat nur die Rolle sich "offline" Artikel vorab ansehen zu können und sonst keine Rechte. Bei diesem speziellen User soll keine 2 Wege Authentifikation zwingend sein.
Gibt es da eine Möglichkeit das so einzustellen?
Die derzeitigen Einstellugen "Erzwungen für alle REDAXO-CMS Benutzer" und "Keine Einschränkungen (Optional für jeden)" passen für meinen Fall beide nicht ganz.
Oder kann ich die 2 Wege Authentifikation bei diesem User irgendwie manuell deaktivieren?

**Comment by dergel** [comment]
sorry für die späte Antwort. Kann man nicht deaktivieren und gleichzeitig bei den anderen erzwingen. Lässt sich nur so lösen, dass niemand es erzwungen hat aber man das entsprechend kommuniziert und eventuell ein kleines script schreibt wo man prüft, wer kein aktives 2FA hat.
