### ISSUE TITLE
Obwohl noch nicht voll authentifiziert werden Addon-Einbindungen (Outputfilter) bereits durchgeführt

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/2factor_auth#89]
Einbindungen von Addons (z.B. der rexTree-Baum vom be_tools über OP-EP) werden bereits durchgeführt und auf der Einmal-Passwortseite angezeigt.

**Comment by dergel** [comment]
Ich denke, dass dies die jeweiligen AddOns selbst regeln müssten. Der Output Filter ist immer aktiv und wenn sich ein AddOn reinhängt, dann sollte es eher über die Fragmente oder die EPs die an bestimmten Headern im Backend hängen, laufen. Kannst du das Issue bei rexTree Repository reinhängen?
