### ISSUE TITLE
Scope der Deaktivierung unklar

### ISSUE THREAD

**Issue by abra100pro** [FriendsOfREDAXO/2factor_auth#99]
Ich würde die 2-Faktor-Authentifizierung Deaktivierung anders formulieren, so dass klar ist, dass das nur für den aktuellen User an der Stelle gilt:

**Ideal:**

Aktuell ist eine OTP-2-Faktor-Authentifizierung für [username] aktiviert.

((Button Label:)): 
2-Faktor-Authentifizierung für [username] deaktivieren.

**Falls das mit dem dynamischen usernamen nicht geht, dann:**

Aktuell ist eine OTP-2-Faktor-Authentifizierung aktiviert.

((Button Label:)): 
2-Faktor-Authentifizierung für diesen Benutzer deaktivieren.

Hintergrund:
Wir haben diesen Button nie gedrückt, weil wir befürchtet haben, dass für das ganze Team des Kunden deaktiviert wird und wieder neu eingerichtet werden muss.

**Comment by dergel** [comment]
ist nun drin, Danke für den Hinweis
